### ISSUE TITLE
cannot get tern to work in atom 0.92.0 - also, don't use command-space as key binding

### ISSUE THREAD

**Issue by faddah** [artoale/atom-tern#5]
i have looked at your read me and even dove down into some of the coffeescript files for the tern package - i simply can't understand how to make your package work with atom 0.92.0. i have done cmd-shift-P and typed tern: start server, and tried typing a period ('.') in a javascript file i am working on - no pop-up ever happens to offer me other code choices. am i missing something here? also, you say the key binding is cmd-space, but you should know that in Mac OS X (what i am using, ver. 10.9.2 Mavericks), cmd-space is all ready the system default binding for Spotlight Search, i would bind to another key combination. at the very least, you need to re-write your read me to be far more comprehensive with step-by-step instructions on how to use this and make it work correctly, otherwise your package will be uninstalled by probably everyone.

**Comment by olierxleben** [comment]
same here. Could not get it to work with 0.95.0

**Comment by faddah** [comment]
and it is still happening under the updated Atom 0.96.0 and the atom-tern package 0.2.0.

**Comment by artoale** [comment]
Sorry, been terribly busy lately - yeah, I agree, there are a few problems regarding both readme and binding (and possibly the code too). I've fixed a few bugs and published v0.3.0, can you please check if you're still having problem?
