### ISSUE TITLE
tern seems not work with the latest atom release 0.11.6...

### ISSUE THREAD

**Issue by cocodrino** [artoale/atom-tern#9]
Hi..sorry but seems than tern is not working with the latest atom, I just downloaded atom and tern using apm, click start server but the editor doesn't show any activity...the completition is the standar in the editor...is there something than I could do for check if it's running or a manual run??...please let me know if I can help because I really need to use tern

thanks!!

**Comment by cocodrino** [comment]
Hi again...opening with the dev tools opened I get

Failed to activate package named 'Tern' ReferenceError: editor is not defined
  at Object.<anonymous> (/home/yo/.atom/packages/Tern/lib/tern.coffee:8:13)
  at Object.<anonymous> (/home/yo/.atom/packages/Tern/lib/tern.coffee:1:1)
  at Module._compile (module.js:455:26)

seems than you missed the parenthesis for the editor argument
 update: (editor) ->
        client.update editor.getUri(), editor.getText()

I add them and seems fixed now :D...hope this can help

**Comment by artoale** [comment]
Should be fixed by #10
